application: helloworld
version: 1
runtime: python
api_version: 1
threadsafe: true

runtime_config:
    python_version: 3

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /static
  static_dir: static

- url: /.*
  script: helloworld.application

